### ISSUE TITLE
Pronunciation link takes me to Brian's rendition, but with Salli as the display text

### ISSUE THREAD

**Issue by tcdowney** [reidmit/yapp#2]
## Expected Behavior
Clicking the pronunciation link in the README.md would take me directly to Brian's pronunciation of yapp. The query param `voice=Brian` implies this is what it should do.

## Actual Behavior
Clicking the link takes me to the the pronunciation page with the "Salli" voice selected. However if I click "Read", it does seem to be read through Brian. Is what I'm hearing truly coming from Brian? Or is it Salli? Very confusing behavior. 

Relevant code: https://github.com/reidmit/yapp/blob/main/README.md?plain=1#L1

**Comment by selzoc** [comment]
Looks to me like this issue is due to how the IPA Reader site works.  If you refer to the [scripts.js](http://ipa-reader.xyz/scripts.js) powering the site, there is a `function loadUrlParams()` that _does_ set the voice correctly (so you _are_ hearing Brian), but fails to update the UI
```javascript
function loadUrlParams() {

    // grab url params
    var params = new URLSearchParams(window.location.search);

    // parse/load params
    if (params.has('text')) {
        var text = decodeURIComponent(params.get('text'));
        $('#ipa-text').val(text);
    }

    if (params.has('voice')) {
        var voice = decodeURIComponent(params.get('voice'))
        $('#polly-voice option:selected').val(voice);
    }

    setShareUrl();

}
```

I suspect that an addition of
```javascript
$('div.select-styled').text(VOICES[voice])
```

yielding the complete function
```javascript
function loadUrlParams() {

    // grab url params
    var params = new URLSearchParams(window.location.search);

    // parse/load params
    if (params.has('text')) {
        var text = decodeURIComponent(params.get('text'));
        $('#ipa-text').val(text);
    }

    if (params.has('voice')) {
        var voice = decodeURIComponent(params.get('voice'))
        $('#polly-voice option:selected').val(voice);
        $('div.select-styled').text(VOICES[voice])
    }

    setShareUrl();

}
```

would suffice to fix your issue.  By setting a breakpoint in that file and invoking my proposed fix via the console, the UI was indeed successfully updated.

I'm afraid the good news ends there, unfortunately.  I have not been able to find the source code of the IPA Reader anywhere, and it appears based on the [blog post](https://cuttlesoft.com/blog/pronouncing-things-with-amazons-polly/) that this was a project completed > 3 years ago, so your hope may be slim.  Probably the best thing you could do would be to reach out the author via [Twitter](https://twitter.com/katie_k7r) to see if they'd be amenable to updating their site.

**Comment by reidmit** [comment]
Thank you for the investigation @selzoc 🙏  Since this seems to be a problem with an upstream dependency, I'm going to close this issue. Feel free to try to fix ipa-reader.xyz by contacting the author! Would also welcome a PR to switch our pronunciation link to a similar website that doesn't have this problem.
